### ISSUE TITLE
1.20.1 support

### ISSUE THREAD

**Issue by patman656** [jaredlll08/Clumps#123]

**Comment by MelchiorGaspar** [comment]
yup..
I also ran into this issue with MC v1.20.1
Minecraft says

 Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Clumps' (clumps) 11.0.0.1 with any version that is compatible with:
		 - minecraft 1.20.1
Unmet dependency listing:
	 - Mod 'Clumps' (clumps) 11.0.0.1 requires version 1.20 of 'Minecraft' (minecraft), 
	 - but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

thx for a great mod.

**Comment by Unleashed75** [comment]
Any updates? A few of us would love to this again on our private server for 1.20.1

**Comment by jaredlll08** [comment]
Closed by https://github.com/jaredlll08/Clumps/commit/efb3d1021cf0738a3ca27ff1254e34ac9fd7ff12

**Comment by Unleashed75** [comment]
You are awesome!! I wish I knew enough to help but Thank you, thank you
