### ISSUE TITLE
Crashes at loading when using OptiFine U G1 pre10

### ISSUE THREAD

**Issue by Zemogiter** [jaredlll08/Clumps#29]
Using mod version 5.02
```
Time: 30.03.20 21:19
Description: Initializing game

java.lang.IllegalStateException: No renderer registered for clumps:xp_orb_big
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) ~[1.15.2-forge-31.1.27.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) ~[forge-1.15.2-31.1.27.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.<init>(EntityRendererManager.java:222)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:425)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1048611264 bytes (1000 MB) / 1980596224 bytes (1888 MB) up to 6335102976 bytes (6041 MB)
	CPUs: 8
	JVM Flags: 6 total; -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G -Xmx6144m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	ModLauncher: 5.0.0-milestone.4+67+b1a340b
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.0.0-milestone.1-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.0.4-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.1.27.jar runtimedistcleaner PLUGINSERVICE 
		/preview_OptiFine_1.15.2_HD_U_G1_pre10.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.1.27.jar fml TRANSFORMATIONSERVICE 
	FML: 31.1
	Forge: net.minecraftforge:31.1.27
	FML Language Providers: 
		javafml@31.1
		minecraft@1
	Mod List: 
		doubledoors_1.15.2-1.2.jar Double Doors {doubledoors@1.2 COMMON_SETUP}
		SlimyBoyos-2.0.1.jar SlimyBoyos {slimyboyos@2.0.1 COMMON_SETUP}
		inventoryprofiles-forge-1.15.2-0.2.1.jar Inventory Profiles {inventoryprofiles@0.2.1 COMMON_SETUP}
		mobgrinder-1.3.jar Mob Grinder {mobgrinder@1.3 COMMON_SETUP}
		mining-helmet-1.15.2-1.0.8.jar Mining Helmet {mining_helmet@1.0.8 COMMON_SETUP}
		GoodSkeletonDontStrafe-v1.1.2-1.15.1.jar Good Skeletons Don't Strafe {goodskeletonsdontstrafe@1.1.2 COMMON_SETUP}
		clayconversion-1.15-1.0.jar Clay Conversion {clayconversion@1.0 COMMON_SETUP}
		beta_days-1.15.2-1.1.2.jar Beta Days {beta_days@1.1.2 COMMON_SETUP}
		curiousshulkerboxes-FORGE-1.15.2-2.0.jar Curious Shulker Boxes {curiousshulkerboxes@FORGE-1.15.2-2.0 COMMON_SETUP}
		jei-1.15.2-6.0.0.2.jar Just Enough Items {jei@6.0.0.2 COMMON_SETUP}
		SwordBlockingCombat-v1.3.2-1.15.2.jar Sword Blocking Combat {swordblockingcombat@1.3.2 COMMON_SETUP}
		fishtraps-forge-1.15.2-0.0.5.jar Fish Traps {fishtraps@1.14.4-0.0.4 COMMON_SETUP}
		paperbooks_1.15.2-1.0.jar Paper Books {paperbooks@1.0 COMMON_SETUP}
		caelus-FORGE-1.15.2-2.0-beta1.jar Caelus API {caelus@FORGE-1.15.2-2.0-beta1 COMMON_SETUP}
		humblingb_1.15.2-1.1.jar Humbling Bundle {humblingb@1.1 COMMON_SETUP}
		skeletonhs_1.15.2-1.1.2.jar Skeleton Horse Spawn {skeletonhs@1.1.2 COMMON_SETUP}
		Clumps-5.0.2.jar Clumps {clumps@5.0.2 COMMON_SETUP}
		RingOfRepair-1.15.2-1.1.19.jar Ring of Repair {ring_of_repair@1.1.19 COMMON_SETUP}
		JRFTL+[1.15.2]-1.1.jar JRFTL {jrftl@1.1 COMMON_SETUP}
		Placebo-1.15.2-3.0.2.jar Placebo {placebo@3.0.2 COMMON_SETUP}
		GoatMod-1.15.2-1.1.jar Goat Mod {goatmod@1.0 COMMON_SETUP}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 COMMON_SETUP}
		DimStorage-1.15.2-3.0.3.jar DimStorage {dimstorage@3.0.3 COMMON_SETUP}
		edibleglowst_1.15.2-1.0.jar Edible Glowstone {edibleglowst@1.0 COMMON_SETUP}
		curioofundying-FORGE-1.15.2-3.0.jar Curio of Undying {curioofundying@FORGE-1.15.2-3.0 COMMON_SETUP}
		u_team_core-1.15.2-2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 COMMON_SETUP}
		nhacampfire_1.15.2-1.5.jar No Hostiles Around Campfire {nhacampfire@1.5 COMMON_SETUP}
		cryingghasts_1.15.2-1.0.jar Crying Ghasts {cryingghasts@1.0 COMMON_SETUP}
		Waddles-1.15.2-0.8.5.jar Waddles {waddles@1.15.2-0.8.5 COMMON_SETUP}
		dragondropsel_1.15.2-1.0.jar Dragon Drops Elytra {dragondropsel@1.0 COMMON_SETUP}
		Hwyla-forge-1.10.8-B72_1.15.2.jar Waila {waila@version COMMON_SETUP}
		PackingTape-1.15.2-0.9.5.jar Packing Tape {packingtape@0.9.5 COMMON_SETUP}
		Crafting+Spawn-1.15.2.0.2.1.jar Crafting Spawn {craftingspawn@0.2.1 COMMON_SETUP}
		infinityworkswithallarrows-1.0.jar Infinity works with all arrows {infinityworkswithallarrows@1.0 COMMON_SETUP}
		horsestandstill-1.15.2-1.0.0.jar Stupid Horse Stand Still {horsestandstill@1.15.2-1.0.0 COMMON_SETUP}
		strongfarmland-1.15.2-1.0.0.jar Stronger Farmland Mod {strongfarmland@1.15.2-1.0.0 COMMON_SETUP}
		forge-1.15.2-31.1.27-universal.jar Forge {forge@31.1.27 COMMON_SETUP}
		experienceore-1.0.jar ExperienceOre {experienceore@1.0 COMMON_SETUP}
		ResourcePackOrganizer-1.15.2-v1.1.0.jar Resource Pack Organizer {resourcepackorganizer@1.1.0 COMMON_SETUP}
		corpse-1.15.2-1.0.3.jar Corpse {corpse@1.15.2-1.0.3 COMMON_SETUP}
		replantingcrops_1.15-1.2.jar Replanting Crops {replantingcrops@1.2 COMMON_SETUP}
		forge-1.15.2-31.1.27-client.jar Minecraft {minecraft@1.15.2 COMMON_SETUP}
		mcw-bridges-1.0.4fix-mc1.15.2.jar Macaw's Bridges {mcwbridges@1.0.4 COMMON_SETUP}
		extraanvils-3.0.jar Extra Anvils {extraanvils@3.0 COMMON_SETUP}
		useful_backpacks-1.15.2-1.9.4.63.jar Useful Backpacks {usefulbackpacks@1.9.4.63 COMMON_SETUP}
		BetterCrates-1.15.2-1.0.0.jar Better Crates {bettercrates@1.0.0 COMMON_SETUP}
		Durability101-1.15-0.0.3.jar Durability101 {durability101@0.0.3 COMMON_SETUP}
		sbetterwatersplash-3.1.jar Better Water Splash {sbetterwatersplash@3.1 COMMON_SETUP}
		LagsLib-1.15.2-1.0.0.jar Lag's Lib {lagslib@1.0.0 COMMON_SETUP}
		astikorcarts-1.0.2-1.15.2.jar AstikorCarts {astikorcarts@1.0.2 COMMON_SETUP}
		moveboats_1.15.2-1.1.jar Move Boats {moveboats@1.1 COMMON_SETUP}
		Craftable+Saddles+[1.15.2]-1.3.jar Craftable Saddles {craftable_saddles@1.3 COMMON_SETUP}
		curios-FORGE-1.15.2-2.0.2.jar Curios API {curios@FORGE-1.15.2-2.0.2 COMMON_SETUP}
		Xaeros_Minimap_20.6.0_Forge_1.15.2.jar Xaero's Minimap {xaerominimap@20.6.0 COMMON_SETUP}
		MaterialMaster-v1.1.2-1.15.2.jar Material Master {materialmaster@1.1.2 COMMON_SETUP}
		RingOfBlink-1.15.2-1.1.18.jar Ring of Blink {ring_of_blink@1.1.18 COMMON_SETUP}
		corail_recycler-4.0.3-1.15.2.jar Corail Recycler {corail_recycler@4.0.3 COMMON_SETUP}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE COMMON_SETUP}
		angelring-1.15.2-1.2.0.jar Angel Ring {angelring@1.2.0 COMMON_SETUP}
		obfuscate-0.4.1-1.15.2.jar Obfuscate {obfuscate@0.4.1 COMMON_SETUP}
		vehicle-mod-0.43.5-1.15.2.jar MrCrayfish's Vehicle Mod {vehicle@0.43.5 COMMON_SETUP}
		structurize-0.10.288-ALPHA.jar Structurize {structurize@0.10.288-ALPHA COMMON_SETUP}
		grindr-1.15.2-0.0.1.4.jar Grindr {grindr@1.15.2-0.0.1.4 COMMON_SETUP}
		worldedit-forge-mc1.15.2-7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c COMMON_SETUP}
		minecolonies-0.10.771-RELEASE-universal.jar Minecolonies {minecolonies@0.10.771-RELEASE COMMON_SETUP}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 COMMON_SETUP}
		mcw-roofs-1.0.2-mc1.15.2_1.15.1.jar Macaw's Roofs {mcwroofs@1.0.2 COMMON_SETUP}
		furniture-7.0.0-pre16-1.15.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre16 COMMON_SETUP}
		shulkerdt_1.15.2-1.1.jar Shulker Drops Two {shulkerdt@1.1 COMMON_SETUP}
		mobcatcher-2.2.jar Mob Catcher {mobcatcher@2.2 COMMON_SETUP}
		curiouselytra-FORGE-1.15.2-2.0.jar Curious Elytra {curiouselytra@FORGE-1.15.2-2.0 COMMON_SETUP}
		globalxp-1.15.2-v1.4.11.jar Global XP {globalxp@v1.4.11 COMMON_SETUP}
		cherishedworlds-FORGE-1.15.2-3.0.jar Cherished Worlds {cherishedworlds@FORGE-1.15.2-3.0 COMMON_SETUP}
		earthsanimals-1.15.1-0.0.4-beta.jar Earths Animals {earthsanimals@1.15.1-0.0.4-beta COMMON_SETUP}
		RingOfReturn-1.15.2-1.0.1.jar Ring of Return {ring_of_return@1.0.1 COMMON_SETUP}
		incubation-1.0.2-1.15.2.jar Incubation {incubation@1.0.2 COMMON_SETUP}
		strayspawn_1.15.2-1.0.jar Stray Spawn {strayspawn@1.0 COMMON_SETUP}
		GameMenuModOption-1.15.2-1.2.jar GameMenuModOption {gamemenumodoption@1.2 COMMON_SETUP}
		lootbagmod-1.15.1-1.5.1.jar Loot Bag Mod {lootbagmod@1.15.1-1.5.1 COMMON_SETUP}
		bigbuckets-1.1.0.jar BigBuckets {bigbuckets@1.1.0 COMMON_SETUP}
		BetterAdvancements-1.15.2-0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 COMMON_SETUP}
	Launched Version: 1.15.2-forge-31.1.27
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1080 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.75, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 8x Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre10
	OptiFine Build: 20200327-015852
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 445.75
	OpenGlRenderer: GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
```

**Comment by jaredlll08** [comment]
Optifine isn't compatible with forge.
