### ISSUE TITLE
A crash

### ISSUE THREAD

**Issue by jklw10** [jaredlll08/Clumps#48]
seems pretty uncommon but once a crash type is there it's not going away on it's own and i'd rather have no crashes than random :)

```
[25Jan2021 17:21:35.891] [Netty Server IO #3/ERROR] [net.minecraft.network.NettyPacketEncoder/]: java.lang.NullPointerException
[25Jan2021 17:23:18.278] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2705/617304845@424ac19c
		2: ASM: class com.endertech.minecraft.forge.world.GameWorld$WorldData onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		3: ASM: net.quetzi.morpheus.helpers.MorpheusEventHandler@72f56f56 worldTickEvent(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		4: ASM: class com.simibubi.create.events.CommonEvents onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		5: ASM: class sonar.fluxnetworks.register.CommonEventHandler onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		6: ASM: class vazkii.quark.addons.oddities.magnetsystem.MagnetSystem tick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		7: ASM: com.refinedmods.refinedstorage.apiimpl.network.NetworkListener@29d0c30f onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		8: ASM: vazkii.quark.content.automation.module.FeedingTroughModule@62f61ef9 buildTroughSet(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		9: ASM: vazkii.quark.content.automation.module.PistonsMoveTileEntitiesModule@33297310 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
		10: ASM: vazkii.quark.content.tweaks.module.ImprovedSleepingModule@5af8c848 onWorldTick(Lnet/minecraftforge/event/TickEvent$WorldTickEvent;)V
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.remove(Unknown Source)
	at com.blamejared.clumps.Clumps.update(Clumps.java:60)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641)
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232)
	at java.lang.Thread.run(Unknown Source)

[25Jan2021 17:23:18.397] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_271]
	at java.util.ArrayList$Itr.remove(Unknown Source) ~[?:1.8.0_271]
	at com.blamejared.clumps.Clumps.update(Clumps.java:60) ~[clumps:6.0.0.13]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:100) ~[forge:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:856) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) ~[?:?]
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]
[25Jan2021 17:23:19.598] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID c740e20b-e9ec-4f1a-b965-82fe1d5e797b
```

**Comment by jaredlll08** [comment]
Mc version?
Clumps version?
do you have that Mc multi threading mod installed?
do you have performant installed?

**Comment by jklw10** [comment]
mc: 1.16.4
clumps: 6.0.0.13
performant installed.
AI-improvements mod.

**Comment by jaredlll08** [comment]
Link to AI improvements?

Also I'm going to have to ask that you try reproduce without performant please

**Comment by jklw10** [comment]
should i just make a complete mod list then?
or just the performance / core editing ones?

**Comment by jklw10** [comment]
forge version 35.1.37

https://www.curseforge.com/minecraft/mc-mods/ai-improvements
https://www.curseforge.com/minecraft/mc-mods/mixinbootstrap
quark affects some core features and performance somewhat
create adds alot but not sure if it has performance changes.

it was a serverside crash so no client side features probably affected it.

i wasn't the one who actually caused the crash but it has worked just normally before

there was ALOT of xp tho. 

apostheosis adds an enchantment that turns loot drops into just xp drops.

what i can see from the crash report tho is that only this mod's and or forge's events were ever handled while doing this so.

also recreating this even with all the mods will be pretty difficult since the same xp farm has been run with clumps for a few days without issue so this is a rare crash.

if you want the world file and mod pack for testing i can provide that?

**Comment by jklw10** [comment]
seems like an upgrade with create's belts affected it somehow since now it crashes often. i'll try to remove those and see if i can make it crash again

**Comment by jaredlll08** [comment]
I'm just going to say that the issue is caused by performant, like there is a reason that immersive engineering guys don't accept reports with performant, it does a number on conveyor belt type blocks.

Create belts should have no impact on Clumps.

**Comment by jklw10** [comment]
well what i just tested removing the belts fixed the crashing issue. so it's probably a combination of belts+clumps+performant

**Comment by jaredlll08** [comment]
Well remove performant and see.

**Comment by jklw10** [comment]
hmm. i am sorry for doing this but i'll be fine with this fix of just not using belts.

i don't have the patience to start minecraft multiple times at the moment atleast.
i might try tomorrow with more energy unless you want to just dismiss this issue?

**Comment by jaredlll08** [comment]
Im telling you that belts have nothing to do with Clumps.

The issue is with performant, and I have no interest in trying to support that mod. 


You're welcome to re-open this issue if you can reproduce without Performant.
