### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by LlubNek** [jaredlll08/Clumps#55]
Minecraft crashed while I was killing a ridiculous number of silverfish...
```
[15:59:44] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_242] {}
	at java.util.ArrayList$Itr.remove(ArrayList.java:873) ~[?:1.8.0_242] {}
	at com.blamejared.clumps.Clumps.update(Clumps.java:65) ~[clumps:6.0.0.17] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at com.performant.coremod.event.EventHandlerB.post(EventHandlerB.java:175) ~[performant:1.16.2-4-3.30m] {re:mixin,re:classloading}
	at com.performant.coremod.event.EventHandlerB.onPostWorldTick(EventHandlerB.java:74) ~[performant:1.16.2-4-3.30m] {re:mixin,re:classloading}
	at net.minecraftforge.fml.hooks.BasicEventHooks.onPostWorldTick(BasicEventHooks.java:524) ~[forge:?] {re:mixin,re:classloading,pl:mixin:APP:performant.mixins.json:forge.BasicEventHooksMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:857) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default,pl:mixin:APP:smoothboot.mixins.json:client.IntegratedServerMixin,pl:mixin:APP:notenoughcrashes.mixins.json:client.MixinIntegratedServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
```
Clumps-6.0.0.17.jar
Minecraft 1.16.5
Forge 36.0.42

[crash-2021-02-21_15.59.45-server.txt](https://github.com/jaredlll08/Clumps/files/6018482/crash-2021-02-21_15.59.45-server.txt)
[latest.log](https://github.com/jaredlll08/Clumps/files/6018483/latest.log)

**Comment by jaredlll08** [comment]
Remove performant.

**Comment by jaredlll08** [comment]
Actually no.

@someaddons what exactly am I doing wrong that causes the crash?

**Comment by jaredlll08** [comment]
I believe this has been fixed by performant.
